site_name: PYDAQ
site_url: https://samirmartins.github.io/pydaq/
nav:
  - Home: index.md
  - Data Acquisition:
      - NIDAQ: get_data_nidaq.md
      - Arduino: get_data_arduino.md
  - Sending Data:
      - NIDAQ: send_data_nidaq.md
      - Arduino: send_data_arduino.md
  - Step Response:
      - NIDAQ: step_response_nidaq.md
      - Arduino: step_response_arduino.md
  - Examples:
    - NIDAQ Examples: examples_nidaq.md
    - Arduino Examples: examples_arduino.md

theme:
  name: material