[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
dynamic = ["dependencies"]
name = "pydaq"
version = "0.0.1"
authors = [
  { name="Samir Angelo Milani Martins", email="milani.martins@gmail.com" },
]

description = "Data Acquisition with Python and National Instruments using Graphical Interface"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/samirmartins/pydaqmx"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}